networks:
  toubilib.net:
    driver: bridge

services:
  api.toubilib:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprati.db
      - toubiauth.db
      - toubirdv.db
      - toubipat.db
    env_file: ./app/config/.env
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  toubiprati.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${PRAT_USERNAME}
      POSTGRES_PASSWORD: ${PRAT_PASSWORD}
      POSTGRES_DB: ${PRAT_DATABASE}
    ports:
      - '5432:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  toubiauth.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${AUTH_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_PASSWORD}
      POSTGRES_DB: ${AUTH_DATABASE}
    ports:
      - '5433:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  toubirdv.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${RDV_USERNAME}
      POSTGRES_PASSWORD: ${RDV_PASSWORD}
      POSTGRES_DB: ${RDV_DATABASE}
    ports:
      - '5434:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  toubipat.db:
    image: 'postgres:latest'
    env_file:
      - ./app/config/.env
    environment:
      POSTGRES_USER: ${PAT_USERNAME}
      POSTGRES_PASSWORD: ${PAT_PASSWORD}
      POSTGRES_DB: ${PAT_DATABASE}
    ports:
      - '5435:5432'
    networks:
      - toubilib.net
    volumes:
      - ./sql:/var/sql

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - toubilib.net